### ISSUE TITLE
main.py, line 250, in manage_strategy key error intc

### ISSUE THREAD

**Issue by pannet1** [pannet1/halo-hash#5]
```|                 quantity                 |         6          |
+------------------------------------------+--------------------+
Traceback (most recent call last):
  File "/home/nitesh/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'intc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nitesh/not_venv/halo-hash/halo_hash/main.py", line 689, in <module>
    execute_strategy(
  File "/home/nitesh/not_venv/halo-hash/halo_hash/main.py", line 475, in execute_strategy
    manage_strategy(sym_config, broker, ws)
  File "/home/nitesh/not_venv/halo-hash/halo_hash/main.py", line 250, in manage_strategy
    condition_1 = latest_record["intc"].item() < latest_record["into"].item()
                  ~~~~~~~~~~~~~^^^^^^^^
  File "/home/nitesh/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nitesh/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'intc'
```

**Comment by MaheswaranPalaniselvan** [comment]
converted ha column headers to follow into, inth, intc, intl format
